# Generated by Django 3.2.23 on 2023-11-24 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='clearance',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
