# Generated by Django 3.2.23 on 2023-12-18 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_review_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='deals',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='new_arrival',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
