# Generated by Django 4.2.7 on 2023-12-18 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20231218_0633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='deals',
        ),
        migrations.RemoveField(
            model_name='product',
            name='new_arrival',
        ),
    ]
